Repository Sylius/ShopApiPlugin, pull requests merged in 2018-11, with the labels that each got.

#334 Added documentation for the order endpoint
  doc/swagger.yml
Labels: Documentation

#341 Require missing bundles in dev
  composer.json
Labels: Maintenance

#344 Use fallback locale from channel in taxon-related endpoints
  spec/Http/RequestBasedLocaleProviderSpec.php
  src/Controller/Taxon/ShowTaxonDetailsAction.php
  src/Controller/Taxon/ShowTaxonTreeAction.php
  src/Http/RequestBasedLocaleProvider.php
  src/Http/RequestBasedLocaleProviderInterface.php
  src/Resources/config/services.xml
  src/Resources/config/services/actions/taxon.xml
  src/Resources/config/services/http.xml
  tests/Controller/TaxonShowDetailsApiTest.php
  tests/Controller/TaxonShowTreeApiTest.php
Labels: New Feature

#356 Add better description and docs link in README
  README.md
Labels: Documentation
