Repository Sylius/ShopApiPlugin, pull requests merged in 2019-07, with the labels that each got.

#455 Adding created date to product review endpoint
  doc/swagger.yml
  spec/Factory/Product/ProductReviewViewFactorySpec.php
  src/Factory/Product/ProductReviewViewFactory.php
  src/View/Product/ProductReviewView.php
  tests/Responses/Expected/product/product_review_list_page_by_code_response.json
  tests/Responses/Expected/product/product_review_list_page_by_slug_response.json
Labels: New Feature

#467 Quick fix after static analysis
  src/Controller/Checkout/ShowAvailableShippingMethodsAction.php
Labels: Bug

#469 [Docs][Order] Update docs after removing channel code from order routes
  doc/swagger.yml
Labels: Documentation

#474 Update README.md
  README.md
Labels: Maintenance

#477 Update README.md
  README.md
Labels: Maintenance

#475 [POC] Another approach to the command providers
  spec/CommandProvider/ChannelBasedCommandProviderSpec.php
  spec/CommandProvider/DefaultCommandProviderSpec.php
  spec/Normalizer/RequestCartTokenNormalizerSpec.php
  src/Command/Cart/DropCart.php
  src/Command/Cart/PickupCart.php
  src/Command/CommandInterface.php
  src/CommandProvider/ChannelBasedCommandProvider.php
  src/CommandProvider/ChannelBasedCommandProviderInterface.php
  src/CommandProvider/CommandProviderInterface.php
  src/CommandProvider/DefaultCommandProvider.php
  src/Controller/Cart/DropCartAction.php
  src/Controller/Cart/PickupCartAction.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/ShopApiExtension.php
  src/Normalizer/RequestCartTokenNormalizer.php
  src/Request/Cart/DropCartRequest.php
  src/Request/Cart/PickupCartRequest.php
  src/Request/ChannelBasedRequestInterface.php
  src/Request/RequestInterface.php
  src/Resources/config/services.xml
  src/Resources/config/services/actions/cart.xml
  src/Resources/config/services/command_providers.xml
  src/Resources/config/services/command_providers/cart.xml
  tests/Request/DropCartRequestTest.php
Labels: RFC

#486 [Maintenance] Minor cs fixes
  src/EventListener/CartBlamerListener.php
  src/Resources/config/services.xml
Labels: Maintenance

#487 [Customer] Extract customer enabling logic to custom handler
  spec/Command/Customer/EnableCustomerSpec.php
  spec/EventListener/UserRegistrationListenerSpec.php
  spec/Handler/Customer/EnableCustomerHandlerSpec.php
  src/Command/Customer/EnableCustomer.php
  src/EventListener/UserRegistrationListener.php
  src/Handler/Customer/EnableCustomerHandler.php
  src/Resources/config/services/handler/customer.xml
Labels: Minor

#489 [HotFix] Try to fix Travis
  .travis.yml
Labels: Bug, Maintenance

#499 [AddressBook] Fixes for set default address action
  src/Controller/AddressBook/SetDefaultAddressAction.php
Labels: Minor

#500 [Docs] Upgrade file fix
  UPGRADE.md
Labels: Maintenance

#503 Add onHand to product response
  doc/swagger.yml
  spec/Factory/Product/ProductVariantViewFactorySpec.php
  src/Factory/Product/ProductVariantViewFactory.php
  src/Resources/config/serializer/Product/ProductVariantView.yml
  src/View/Product/ProductVariantView.php
  tests/DataFixtures/ORM/shop.yml
  tests/Responses/Expected/cart/add_multiple_products_to_cart_response.json
  tests/Responses/Expected/cart/add_multiple_products_to_new_cart_response.json
  tests/Responses/Expected/cart/add_product_variant_based_on_options_multiple_times_to_cart_response.json
  tests/Responses/Expected/cart/add_product_variant_based_on_options_to_cart_response.json
  tests/Responses/Expected/cart/add_product_variant_multiple_times_to_cart_response.json
  tests/Responses/Expected/cart/add_product_variant_to_cart_response.json
  tests/Responses/Expected/cart/add_simple_product_multiple_times_to_cart_response.json
  tests/Responses/Expected/cart/add_simple_product_to_cart_response.json
  tests/Responses/Expected/cart/add_simple_product_to_new_cart_response.json
  tests/Responses/Expected/cart/cart_with_coupon_based_promotion_applied_response.json
  tests/Responses/Expected/cart/filled_cart_with_product_variant_summary_response.json
  tests/Responses/Expected/cart/filled_cart_with_simple_product_summary_response.json
  tests/Responses/Expected/cart/german_filled_cart_with_product_variant_summary_response.json
  tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
  tests/Responses/Expected/cart/recalculated_cart_after_log_in.json
  tests/Responses/Expected/cart/reprocessed_cart_after_deleting_an_item.json
  tests/Responses/Expected/checkout/cart_addressed_response.json
  tests/Responses/Expected/checkout/cart_addressed_with_different_shipping_and_billing_address_response.json
  tests/Responses/Expected/checkout/cart_with_chosen_payment_response.json
  tests/Responses/Expected/checkout/cart_with_chosen_shipment_response.json
  tests/Responses/Expected/checkout/cart_with_chosen_shipment_with_per_item_rate_response.json
  tests/Responses/Expected/checkout/modified_cart_with_chosen_shipment_with_per_item_rate_response.json
  tests/Responses/Expected/order/order_details_response.json
  tests/Responses/Expected/order/order_details_response_guest.json
  tests/Responses/Expected/order/orders_list_response.json
  tests/Responses/Expected/product/german_product_list_page_by_code_response.json
  tests/Responses/Expected/product/german_product_list_page_by_slug_response.json
  tests/Responses/Expected/product/german_product_with_options_details_page.json
  tests/Responses/Expected/product/german_simple_product_details_page.json
  tests/Responses/Expected/product/limited_product_list_page_by_code_response.json
  tests/Responses/Expected/product/limited_product_list_page_by_slug_response.json
  tests/Responses/Expected/product/product_list_latest_2_response.json
  tests/Responses/Expected/product/product_list_latest_4_response.json
  tests/Responses/Expected/product/product_list_page_by_code_response.json
  tests/Responses/Expected/product/product_list_page_by_slug_response.json
  tests/Responses/Expected/product/product_t_shirt_list_page_by_code_response.json
  tests/Responses/Expected/product/product_t_shirt_list_page_by_slug_response.json
  tests/Responses/Expected/product/product_with_options_details_page.json
  tests/Responses/Expected/product/product_with_variant_details_page.json
  tests/Responses/Expected/product/simple_product_details_page.json
Labels: New Feature
