Repository Sylius/ShopApiPlugin, pull requests merged in 2019-09, with the labels that each got.

#522 Fix errors in swagger file
  doc/swagger.yml
  spec/Handler/Cart/PickupCartHandlerSpec.php
Labels: Documentation

#514 Adding a Cookbook
  README.md
  doc/Cookbook.md
  doc/Workflow.png
Labels: Documentation

#512 Revert "Add onHand to product response"
  doc/swagger.yml
  spec/Factory/Product/ProductVariantViewFactorySpec.php
  src/Factory/Product/ProductVariantViewFactory.php
  src/Resources/config/serializer/Product/ProductVariantView.yml
  src/View/Product/ProductVariantView.php
  tests/DataFixtures/ORM/shop.yml
  tests/Responses/Expected/cart/add_multiple_products_to_cart_response.json
  tests/Responses/Expected/cart/add_multiple_products_to_new_cart_response.json
  tests/Responses/Expected/cart/add_product_variant_based_on_options_multiple_times_to_cart_response.json
  tests/Responses/Expected/cart/add_product_variant_based_on_options_to_cart_response.json
  tests/Responses/Expected/cart/add_product_variant_multiple_times_to_cart_response.json
  tests/Responses/Expected/cart/add_product_variant_to_cart_response.json
  tests/Responses/Expected/cart/add_simple_product_multiple_times_to_cart_response.json
  tests/Responses/Expected/cart/add_simple_product_to_cart_response.json
  tests/Responses/Expected/cart/add_simple_product_to_new_cart_response.json
  tests/Responses/Expected/cart/cart_with_coupon_based_promotion_applied_response.json
  tests/Responses/Expected/cart/filled_cart_with_product_variant_summary_response.json
  tests/Responses/Expected/cart/filled_cart_with_simple_product_summary_response.json
  tests/Responses/Expected/cart/german_filled_cart_with_product_variant_summary_response.json
  tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
  tests/Responses/Expected/cart/recalculated_cart_after_log_in.json
  tests/Responses/Expected/cart/reprocessed_cart_after_deleting_an_item.json
  tests/Responses/Expected/checkout/cart_addressed_response.json
  tests/Responses/Expected/checkout/cart_addressed_with_different_shipping_and_billing_address_response.json
  tests/Responses/Expected/checkout/cart_with_chosen_payment_response.json
  tests/Responses/Expected/checkout/cart_with_chosen_shipment_response.json
  tests/Responses/Expected/checkout/cart_with_chosen_shipment_with_per_item_rate_response.json
  tests/Responses/Expected/checkout/modified_cart_with_chosen_shipment_with_per_item_rate_response.json
  tests/Responses/Expected/order/order_details_response.json
  tests/Responses/Expected/order/order_details_response_guest.json
  tests/Responses/Expected/order/orders_list_response.json
  tests/Responses/Expected/product/german_product_list_page_by_code_response.json
  tests/Responses/Expected/product/german_product_list_page_by_slug_response.json
  tests/Responses/Expected/product/german_product_with_options_details_page.json
  tests/Responses/Expected/product/german_simple_product_details_page.json
  tests/Responses/Expected/product/limited_product_list_page_by_code_response.json
  tests/Responses/Expected/product/limited_product_list_page_by_slug_response.json
  tests/Responses/Expected/product/product_list_latest_2_response.json
  tests/Responses/Expected/product/product_list_latest_4_response.json
  tests/Responses/Expected/product/product_list_page_by_code_response.json
  tests/Responses/Expected/product/product_list_page_by_slug_response.json
  tests/Responses/Expected/product/product_t_shirt_list_page_by_code_response.json
  tests/Responses/Expected/product/product_t_shirt_list_page_by_slug_response.json
  tests/Responses/Expected/product/product_with_options_details_page.json
  tests/Responses/Expected/product/product_with_variant_details_page.json
  tests/Responses/Expected/product/simple_product_details_page.json
Labels: Maintenance

#536 Fix CartBlamerListener without token
  doc/swagger.yml
  src/EventListener/CartBlamerListener.php
  tests/Controller/Customer/LoginApiTest.php
Labels: Bug

#530 Addding assertions for product in current channel
  spec/Checker/ProductInCartChannelCheckerSpec.php
  spec/Handler/Cart/PutOptionBasedConfigurableItemToCartHandlerSpec.php
  spec/Handler/Cart/PutSimpleItemToCartHandlerSpec.php
  spec/Handler/Cart/PutVariantBasedConfigurableItemToCartHandlerSpec.php
  spec/Validator/Product/ProductInCartChannelValidatorSpec.php
  src/Checker/ProductInCartChannelChecker.php
  src/Checker/ProductInCartChannelCheckerInterface.php
  src/Handler/Cart/PutOptionBasedConfigurableItemToCartHandler.php
  src/Handler/Cart/PutSimpleItemToCartHandler.php
  src/Handler/Cart/PutVariantBasedConfigurableItemToCartHandler.php
  src/Request/Cart/PutOptionBasedConfigurableItemToCartRequest.php
  src/Request/Cart/PutSimpleItemToCartRequest.php
  src/Request/Cart/PutVariantBasedConfigurableItemToCartRequest.php
  src/Resources/config/services.xml
  src/Resources/config/services/checker.xml
  src/Resources/config/services/checker/channel.xml
  src/Resources/config/services/handler/cart.xml
  src/Resources/config/services/validators/product.xml
  src/Resources/config/validation/cart/PutOptionBasedConfigutableItemToCartRequest.xml
  src/Resources/config/validation/cart/PutSimpleItemToCartRequest.xml
  src/Resources/config/validation/cart/PutVariantBasedConfigutableItemToCartRequest.xml
  src/Validator/Constraints/ProductInCartChannel.php
  src/Validator/Product/ProductInCartChannelValidator.php
  tests/Controller/Cart/PutItemToCartApiTest.php
  tests/DataFixtures/ORM/channel.yml
  tests/DataFixtures/ORM/shop.yml
  tests/Responses/Expected/cart/product_not_in_cart_channel.json
Labels: Bug

#520 docs(swagger): fix `/carts/{token}/multiple-items`
  doc/swagger.yml
Labels: Documentation

#546 Handle registration for exist customer
  src/Handler/Customer/RegisterCustomerHandler.php
  src/Provider/ShopUserAwareCustomerProvider.php
  src/Resources/config/services/handler/customer.xml
  tests/Controller/Customer/RegisterApiTest.php
Labels: Bug
