Repository Sylius/ShopApiPlugin, pull requests merged in 2019-11, with the labels that each got.

#593 [Checkout] Send confirmation email after checkout is completed
  doc/Cookbook.md
  spec/Command/Customer/SendOrderConfirmationSpec.php
  spec/Event/OrderCompletedSpec.php
  spec/EventListener/Messenger/OrderCompletedListenerSpec.php
  spec/Handler/Cart/CompleteOrderHandlerSpec.php
  spec/Handler/Customer/SendOrderConfirmationHandlerSpec.php
  src/Command/Customer/SendOrderConfirmation.php
  src/Event/OrderCompleted.php
  src/EventListener/Messenger/OrderCompletedListener.php
  src/Handler/Cart/CompleteOrderHandler.php
  src/Handler/Customer/SendOrderConfirmationHandler.php
  src/Mailer/Emails.php
  src/Resources/config/app/sylius_mailer.yml
  src/Resources/config/services.xml
  src/Resources/config/services/handler/cart.xml
  src/Resources/config/services/handler/customer.xml
  src/Resources/views/Email/orderConfirmation.html.twig
  tests/Controller/Checkout/CompleteOrderApiTest.php
Labels: Bug

#605 Update test mockups and fix the build
  tests/Responses/Expected/customer/bad_credentials_response.json
  tests/Responses/Expected/customer/validation_empty_data.json
  tests/Responses/Expected/order/order_details_response.json
  tests/Responses/Expected/order/orders_list_response.json
  tests/Responses/Expected/reviews/add_review_failed_rating.json
Labels: Bug

#602 Loosen dep constraint for Symfony messenger component
  composer.json
Labels: Maintenance

#604 Add missing branch alias
  composer.json
Labels: Maintenance

#607 [CHANGELOG] Generate changelog for v1.0.0-rc.3
  CHANGELOG.md
Labels: Maintenance

#608 Improve documentation
  CHANGELOG.md
  UPGRADE.md
Labels: Documentation
