Repository Sylius/ShopApiPlugin, pull requests merged in 2019-10, with the labels that each got.

#579 Fixing dependencies
  composer.json
  src/Mailer/Emails.php
Labels: Bug, Minor

#578 Fix token generator service for customer's password reset handler
  src/Resources/config/services/handler/customer.xml
Labels: Maintenance, Minor

#586 [Product] Introduce product attribute value view resolvers
  spec/Factory/Product/ProductAttributeValueViewFactorySpec.php
  spec/Factory/Product/ProductAttributeValueViewResolver/DefaultProductAttributeValueViewResolverSpec.php
  spec/Factory/Product/ProductAttributeValueViewResolver/SelectProductAttributeValueViewResolverSpec.php
  src/Factory/Product/ProductAttributeValueViewFactory.php
  src/Factory/Product/ProductAttributeValueViewFactoryInterface.php
  src/Factory/Product/ProductAttributeValueViewResolver/DefaultProductAttributeValueViewResolver.php
  src/Factory/Product/ProductAttributeValueViewResolver/ProductAttributeValueViewResolverInterface.php
  src/Factory/Product/ProductAttributeValueViewResolver/SelectProductAttributeValueViewResolver.php
  src/Resources/config/services/factories/product.xml
  src/View/Product/ProductAttributeValueView.php
  tests/Application/config/packages/sylius_shop_api.yaml
  tests/Controller/Product/ShowDetailsByCodeApiTest.php
  tests/DataFixtures/ORM/product_with_attributes.yml
  tests/DataFixtures/ORM/shop.yml
  tests/Responses/Expected/cart/add_multiple_products_to_cart_response.json
  tests/Responses/Expected/cart/add_multiple_products_to_new_cart_response.json
  tests/Responses/Expected/cart/add_simple_product_multiple_times_to_cart_response.json
  tests/Responses/Expected/cart/add_simple_product_to_cart_response.json
  tests/Responses/Expected/cart/add_simple_product_to_new_cart_response.json
  tests/Responses/Expected/cart/cart_with_coupon_based_promotion_applied_response.json
  tests/Responses/Expected/cart/filled_cart_with_simple_product_summary_response.json
  tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
  tests/Responses/Expected/cart/recalculated_cart_after_log_in.json
  tests/Responses/Expected/cart/reprocessed_cart_after_deleting_an_item.json
  tests/Responses/Expected/checkout/cart_addressed_response.json
  tests/Responses/Expected/checkout/cart_addressed_with_different_shipping_and_billing_address_response.json
  tests/Responses/Expected/checkout/cart_with_chosen_payment_response.json
  tests/Responses/Expected/checkout/cart_with_chosen_shipment_response.json
  tests/Responses/Expected/checkout/cart_with_chosen_shipment_with_per_item_rate_response.json
  tests/Responses/Expected/checkout/modified_cart_with_chosen_shipment_with_per_item_rate_response.json
  tests/Responses/Expected/order/order_details_response.json
  tests/Responses/Expected/order/order_details_response_guest.json
  tests/Responses/Expected/order/orders_list_response.json
  tests/Responses/Expected/product/german_product_list_page_by_code_response.json
  tests/Responses/Expected/product/german_product_list_page_by_slug_response.json
  tests/Responses/Expected/product/german_product_with_attributes_details_page.json
  tests/Responses/Expected/product/german_product_with_options_details_page.json
  tests/Responses/Expected/product/german_simple_product_details_page.json
  tests/Responses/Expected/product/product_list_latest_2_response.json
  tests/Responses/Expected/product/product_list_latest_4_response.json
  tests/Responses/Expected/product/product_list_page_by_code_response.json
  tests/Responses/Expected/product/product_list_page_by_slug_response.json
  tests/Responses/Expected/product/product_with_attributes_details_page.json
  tests/Responses/Expected/product/product_with_options_details_page.json
  tests/Responses/Expected/product/simple_product_details_page.json
Labels: RFC

#573 Extending customer details tests
  src/Command/Customer/UpdateCustomer.php
  tests/Controller/Customer/LoggedInCustomerDetailsActionTest.php
  tests/Controller/Customer/UpdateCustomerApiTest.php
  tests/DataFixtures/ORM/customer.yml
  tests/Responses/Expected/address_book/add_address_response.json
  tests/Responses/Expected/address_book/show_address_book_response.json
  tests/Responses/Expected/customer/logged_in_customer_details_response.json
  tests/Responses/Expected/customer/update_customer.json
Labels: Maintenance
