Repository Sylius/ShopApiPlugin, pull requests merged in 2020-02, with the labels that each got.

#630 docs: in PlacedOrder definition add number property
  doc/swagger.yml
Labels: Documentation

#621 Add email validation to RequestResetPassword
  UPGRADE.md
  doc/swagger.yml
  spec/Handler/Customer/GenerateResetPasswordTokenHandlerSpec.php
  spec/Handler/Customer/SendResetPasswordTokenHandlerSpec.php
  src/Controller/Customer/RequestPasswordResettingAction.php
  src/Exception/UserNotFoundException.php
  src/Handler/Customer/GenerateResetPasswordTokenHandler.php
  src/Handler/Customer/SendResetPasswordTokenHandler.php
  src/Resources/config/services/actions/customer.xml
  src/Resources/config/validation/customer/GenerateResetPasswordTokenRequest.xml
  tests/Controller/Customer/RequestPasswordResettingApiTest.php
  tests/Responses/Expected/customer/request_reset_password_empty_email.json
  tests/Responses/Expected/customer/request_reset_password_failed_email.json
Labels: Bug, Minor

#508 Add availibility property to ProductVariantView
  spec/Factory/Product/ProductVariantViewFactorySpec.php
  src/Factory/Product/ProductVariantViewFactory.php
  src/Resources/config/serializer/Product/ProductVariantView.yml
  src/Resources/config/services/factories/product.xml
  src/View/Product/ProductVariantView.php
  tests/Responses/Expected/cart/add_multiple_products_to_cart_response.json
  tests/Responses/Expected/cart/add_multiple_products_to_new_cart_response.json
  tests/Responses/Expected/cart/add_product_variant_based_on_options_multiple_times_to_cart_response.json
  tests/Responses/Expected/cart/add_product_variant_based_on_options_to_cart_response.json
  tests/Responses/Expected/cart/add_product_variant_multiple_times_to_cart_response.json
  tests/Responses/Expected/cart/add_product_variant_to_cart_response.json
  tests/Responses/Expected/cart/add_simple_product_multiple_times_to_cart_response.json
  tests/Responses/Expected/cart/add_simple_product_to_cart_response.json
  tests/Responses/Expected/cart/add_simple_product_to_new_cart_response.json
  tests/Responses/Expected/cart/cart_with_coupon_based_promotion_applied_response.json
  tests/Responses/Expected/cart/filled_cart_with_product_variant_summary_response.json
  tests/Responses/Expected/cart/filled_cart_with_simple_product_summary_response.json
  tests/Responses/Expected/cart/german_filled_cart_with_product_variant_summary_response.json
  tests/Responses/Expected/cart/german_filled_cart_with_simple_product_summary_response.json
  tests/Responses/Expected/cart/recalculated_cart_after_log_in.json
  tests/Responses/Expected/cart/reprocessed_cart_after_deleting_an_item.json
  tests/Responses/Expected/checkout/cart_addressed_response.json
  tests/Responses/Expected/checkout/cart_addressed_with_different_shipping_and_billing_address_response.json
  tests/Responses/Expected/checkout/cart_addressed_with_province_codes_response.json
  tests/Responses/Expected/checkout/cart_with_chosen_payment_response.json
  tests/Responses/Expected/checkout/cart_with_chosen_shipment_response.json
  tests/Responses/Expected/checkout/cart_with_chosen_shipment_with_per_item_rate_response.json
  tests/Responses/Expected/checkout/modified_cart_with_chosen_shipment_with_per_item_rate_response.json
  tests/Responses/Expected/order/order_details_response.json
  tests/Responses/Expected/order/order_details_response_guest.json
  tests/Responses/Expected/order/orders_list_response.json
  tests/Responses/Expected/product/german_product_list_page_by_code_response.json
  tests/Responses/Expected/product/german_product_list_page_by_slug_response.json
  tests/Responses/Expected/product/german_product_with_attributes_details_page.json
  tests/Responses/Expected/product/german_product_with_options_details_page.json
  tests/Responses/Expected/product/german_simple_product_details_page.json
  tests/Responses/Expected/product/limited_product_list_page_by_code_response.json
  tests/Responses/Expected/product/limited_product_list_page_by_slug_response.json
  tests/Responses/Expected/product/product_list_latest_2_response.json
  tests/Responses/Expected/product/product_list_latest_4_response.json
  tests/Responses/Expected/product/product_list_page_by_code_response.json
  tests/Responses/Expected/product/product_list_page_by_slug_response.json
  tests/Responses/Expected/product/product_t_shirt_list_page_by_code_response.json
  tests/Responses/Expected/product/product_t_shirt_list_page_by_slug_response.json
  tests/Responses/Expected/product/product_with_attributes_details_page.json
  tests/Responses/Expected/product/product_with_options_details_page.json
  tests/Responses/Expected/product/product_with_variant_details_page.json
  tests/Responses/Expected/product/simple_product_details_page.json
Labels: New Feature, RFC

#631 Define release cycle for Shop API
  README.md
Labels: Maintenance, RFC

#422 Implemented order available payment methods and order update payment
  doc/swagger.yml
  spec/Command/Order/UpdatePaymentMethodSpec.php
  spec/Factory/Order/PlacedOrderViewFactorySpec.php
  spec/Handler/Order/UpdatePaymentMethodHandlerSpec.php
  spec/Validator/Order/OrderExistsValidatorSpec.php
  src/Command/Order/UpdatePaymentMethod.php
  src/Controller/Order/UpdatePaymentMethodAction.php
  src/Factory/Order/PlacedOrderViewFactory.php
  src/Handler/Order/UpdatePaymentMethodHandler.php
  src/Request/Order/UpdatePaymentMethodRequest.php
  src/Resources/config/routing/order.yml
  src/Resources/config/services/actions/order.xml
  src/Resources/config/services/handler/order.xml
  src/Resources/config/services/validators/order.xml
  src/Resources/config/validation/order/UpdatePaymentMethodRequest.xml
  src/Validator/Constraints/OrderExists.php
  src/Validator/Constraints/PaymentNotPaid.php
  src/Validator/Order/OrderExistsValidator.php
  src/Validator/Order/PaymentNotPaidValidator.php
  src/View/Order/PlacedOrderView.php
  tests/Controller/Order/OrderUpdatePaymentMethodApiTest.php
  tests/Responses/Expected/order/order_details_response.json
  tests/Responses/Expected/order/order_details_response_guest.json
  tests/Responses/Expected/order/orders_list_response.json
Labels: New Feature
