Repository Sylius/ShopApiPlugin, pull requests merged in 2020-01, with the labels that each got.

#622 Upgrade to PHPStan 0.12
  composer.json
  easy-coding-standard.yml
  phpstan.neon
  src/Controller/Customer/CustomerController.php
  src/Factory/Taxon/TaxonDetailsViewFactory.php
  src/Handler/AddressBook/SetDefaultAddressHandler.php
  src/Mapper/AddressMapper.php
  src/Request/Cart/PutSimpleItemToCartRequest.php
  src/Request/Cart/PutVariantBasedConfigurableItemToCartRequest.php
  src/Validator/Cart/CartExistsValidator.php
  src/Validator/Cart/CartItemExistsValidator.php
  src/Validator/Cart/TokenIsNotUsedValidator.php
  src/Validator/Cart/ValidPromotionCouponCodeValidator.php
  src/Validator/ChannelExistsValidator.php
  src/Validator/Customer/ShopUserDoesNotExistValidator.php
  src/Validator/Customer/ShopUserExistsValidator.php
  src/Validator/Customer/VerificationTokenExistsValidator.php
  src/Validator/Product/ConfigurableProductValidator.php
  src/Validator/Product/ProductExistsValidator.php
  src/Validator/Product/ProductVariantExistsValidator.php
  src/Validator/Product/SimpleProductValidator.php
  tests/Controller/AddressBook/SetDefaultAddressApiTest.php
Labels: Maintenance

#624 Removing dead validation for nonexisting class
  src/Resources/config/validation/address_book/RemoveAddressRequest.xml
Labels: Maintenance

#623 Fixing php type errors instead of ignoring them
  phpstan.neon
  src/Command/AddressBook/SetDefaultAddress.php
  src/Command/Cart/ChangeItemQuantity.php
  src/Command/Cart/ChoosePaymentMethod.php
  src/Command/Cart/ChooseShippingMethod.php
  src/Command/Cart/RemoveItemFromCart.php
  src/Factory/Customer/CustomerViewFactory.php
  src/Factory/Customer/CustomerViewFactoryInterface.php
  src/Factory/Product/ProductAttributeValueViewResolver/ProductAttributeValueViewResolverInterface.php
  src/Model/PaginatorDetails.php
  src/Validator/Address/AddressExistsValidator.php
  src/Validator/Address/CountryExistsValidator.php
Labels: Maintenance, Minor

#612 refactor: pass checkout state as criterion to findBy method
  spec/ViewRepository/Order/PlacedOrderViewRepositorySpec.php
  src/ViewRepository/Order/PlacedOrderViewRepository.php
Labels: Bug

#626 More comprehensive error messages for checkout validation
  spec/Validator/Cart/CartReadyForCheckoutValidatorSpec.php
  src/Resources/translations/validators.en.yml
  src/Validator/Cart/CartReadyForCheckoutValidator.php
  src/Validator/Constraints/CartReadyForCheckout.php
  tests/Responses/Expected/checkout/cart_not_ready_for_checkout.json
Labels: Maintenance, Minor
